FROM golang:1.26-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "--build.cmd", "go build -o ./bin/api ./cmd/api", "--build.entrypoint", "./bin/api"]