// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Offer struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	Vehicle     pgtype.Text      `json:"vehicle"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Float8    `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID         int32       `json:"id"`
	Email      string      `json:"email"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Patronymic pgtype.Text `json:"patronymic"`
	Password   string      `json:"password"`
}
