// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOffer = `-- name: AddOffer :one
INSERT INTO offers (user_id, vehicle, description, price) VALUES ($1, $2, $3, $4) RETURNING id
`

type AddOfferParams struct {
	UserID      pgtype.Int4   `json:"user_id"`
	Vehicle     pgtype.Text   `json:"vehicle"`
	Description pgtype.Text   `json:"description"`
	Price       pgtype.Float8 `json:"price"`
}

func (q *Queries) AddOffer(ctx context.Context, arg AddOfferParams) (int32, error) {
	row := q.db.QueryRow(ctx, addOffer,
		arg.UserID,
		arg.Vehicle,
		arg.Description,
		arg.Price,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addUser = `-- name: AddUser :one
INSERT INTO users (email, first_name, last_name, patronymic, password) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type AddUserParams struct {
	Email      string      `json:"email"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Patronymic pgtype.Text `json:"patronymic"`
	Password   string      `json:"password"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, addUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Password,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAllOffers = `-- name: GetAllOffers :many
SELECT id, user_id, vehicle, description, price, created_at FROM offers
`

func (q *Queries) GetAllOffers(ctx context.Context) ([]Offer, error) {
	rows, err := q.db.Query(ctx, getAllOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Vehicle,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOfferById = `-- name: GetOfferById :one
SELECT id, user_id, vehicle, description, price, created_at FROM offers WHERE id = $1
`

func (q *Queries) GetOfferById(ctx context.Context, id int32) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferById, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Vehicle,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, patronymic, password FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Password,
	)
	return i, err
}

const removeOffer = `-- name: RemoveOffer :exec
DELETE FROM offers WHERE id = $1
`

func (q *Queries) RemoveOffer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeOffer, id)
	return err
}
