// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOffer = `-- name: AddOffer :one
INSERT INTO offers (user_id, make, model, year, gearbox, mileage, color, fuel, price, owners, negotiable, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type AddOfferParams struct {
	UserID      pgtype.Int4        `json:"user_id"`
	Make        pgtype.Text        `json:"make"`
	Model       pgtype.Text        `json:"model"`
	Year        pgtype.Int2        `json:"year"`
	Gearbox     NullVehicleGearbox `json:"gearbox"`
	Mileage     pgtype.Int4        `json:"mileage"`
	Color       pgtype.Text        `json:"color"`
	Fuel        NullVehicleFuel    `json:"fuel"`
	Price       pgtype.Int4        `json:"price"`
	Owners      pgtype.Int2        `json:"owners"`
	Negotiable  pgtype.Bool        `json:"negotiable"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) AddOffer(ctx context.Context, arg AddOfferParams) (int32, error) {
	row := q.db.QueryRow(ctx, addOffer,
		arg.UserID,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Gearbox,
		arg.Mileage,
		arg.Color,
		arg.Fuel,
		arg.Price,
		arg.Owners,
		arg.Negotiable,
		arg.Description,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addOfferPhoto = `-- name: AddOfferPhoto :one
INSERT INTO offer_photos (offer_id, filename, position) VALUES ($1, $2, $3) RETURNING id
`

type AddOfferPhotoParams struct {
	OfferID  pgtype.Int4 `json:"offer_id"`
	Filename string      `json:"filename"`
	Position int16       `json:"position"`
}

func (q *Queries) AddOfferPhoto(ctx context.Context, arg AddOfferPhotoParams) (int32, error) {
	row := q.db.QueryRow(ctx, addOfferPhoto, arg.OfferID, arg.Filename, arg.Position)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addRefreshToken = `-- name: AddRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id
`

type AddRefreshTokenParams struct {
	UserID    pgtype.Int4      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (int32, error) {
	row := q.db.QueryRow(ctx, addRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addUser = `-- name: AddUser :one
INSERT INTO users (email, full_name, password, phone_number) VALUES ($1, $2, $3, $4) RETURNING id
`

type AddUserParams struct {
	Email       string      `json:"email"`
	FullName    pgtype.Text `json:"full_name"`
	Password    string      `json:"password"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, addUser,
		arg.Email,
		arg.FullName,
		arg.Password,
		arg.PhoneNumber,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const getAllOffers = `-- name: GetAllOffers :many
SELECT o.id, o.user_id, o.make, o.model, o.year, o.gearbox, o.mileage, o.color, o.fuel, o.price, o.owners, o.negotiable, o.description, o.archived_at, o.created_at, COALESCE(p.id, 0) AS photo_id, COALESCE(p.filename, '') AS photo_filename
FROM offers o
LEFT JOIN LATERAL (
    SELECT id, filename FROM offer_photos WHERE offer_id = o.id ORDER BY position LIMIT 1
) p ON true WHERE o.archived_at IS NULL
`

type GetAllOffersRow struct {
	ID            int32              `json:"id"`
	UserID        pgtype.Int4        `json:"user_id"`
	Make          pgtype.Text        `json:"make"`
	Model         pgtype.Text        `json:"model"`
	Year          pgtype.Int2        `json:"year"`
	Gearbox       NullVehicleGearbox `json:"gearbox"`
	Mileage       pgtype.Int4        `json:"mileage"`
	Color         pgtype.Text        `json:"color"`
	Fuel          NullVehicleFuel    `json:"fuel"`
	Price         pgtype.Int4        `json:"price"`
	Owners        pgtype.Int2        `json:"owners"`
	Negotiable    pgtype.Bool        `json:"negotiable"`
	Description   pgtype.Text        `json:"description"`
	ArchivedAt    pgtype.Timestamp   `json:"archived_at"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	PhotoID       int32              `json:"photo_id"`
	PhotoFilename string             `json:"photo_filename"`
}

func (q *Queries) GetAllOffers(ctx context.Context) ([]GetAllOffersRow, error) {
	rows, err := q.db.Query(ctx, getAllOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOffersRow
	for rows.Next() {
		var i GetAllOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Gearbox,
			&i.Mileage,
			&i.Color,
			&i.Fuel,
			&i.Price,
			&i.Owners,
			&i.Negotiable,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.PhotoID,
			&i.PhotoFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOfferById = `-- name: GetOfferById :one
SELECT id, user_id, make, model, year, gearbox, mileage, color, fuel, price, owners, negotiable, description, archived_at, created_at FROM offers WHERE id = $1
`

func (q *Queries) GetOfferById(ctx context.Context, id int32) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferById, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Gearbox,
		&i.Mileage,
		&i.Color,
		&i.Fuel,
		&i.Price,
		&i.Owners,
		&i.Negotiable,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOffersCount = `-- name: GetOffersCount :one
SELECT count(*) FROM offers
`

func (q *Queries) GetOffersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getOffersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPhotosByOfferID = `-- name: GetPhotosByOfferID :many
SELECT id, offer_id, filename, position FROM offer_photos WHERE offer_id = $1 ORDER BY position
`

type GetPhotosByOfferIDRow struct {
	ID       int32       `json:"id"`
	OfferID  pgtype.Int4 `json:"offer_id"`
	Filename string      `json:"filename"`
	Position int16       `json:"position"`
}

func (q *Queries) GetPhotosByOfferID(ctx context.Context, offerID pgtype.Int4) ([]GetPhotosByOfferIDRow, error) {
	rows, err := q.db.Query(ctx, getPhotosByOfferID, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhotosByOfferIDRow
	for rows.Next() {
		var i GetPhotosByOfferIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.Filename,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM refresh_tokens WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, password, phone_number FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Password,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, password, phone_number FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Password,
		&i.PhoneNumber,
	)
	return i, err
}

const removeOffer = `-- name: RemoveOffer :exec
DELETE FROM offers WHERE id = $1
`

func (q *Queries) RemoveOffer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeOffer, id)
	return err
}

const setOfferArchivedAt = `-- name: SetOfferArchivedAt :exec
UPDATE offers SET archived_at = $1 WHERE id = $2
`

type SetOfferArchivedAtParams struct {
	ArchivedAt pgtype.Timestamp `json:"archived_at"`
	ID         int32            `json:"id"`
}

func (q *Queries) SetOfferArchivedAt(ctx context.Context, arg SetOfferArchivedAtParams) error {
	_, err := q.db.Exec(ctx, setOfferArchivedAt, arg.ArchivedAt, arg.ID)
	return err
}
